package com.ftn.sbnz.model.enums;

public enum SymptomType {
    WARNING_CHECK_ENGINE,
    WARNING_COOLANT_TEMP,
    WARNING_OIL_PRESSURE,
    WARNING_BATTERY,
    BLACK_EXHAUST_SMOKE,
    WHITE_EXHAUST_SMOKE,
    POWER_LOSS,
    INCREASED_FUEL_CONSUMPTION,
    COLD_HEATER_OUTPUT,
    BRAKE_SQUEAL,
    STEERING_WHEEL_VIBRATION,
    TPMS_WARNING,
    GEAR_CHANGE_JERK
}
